name: Check code style
on: push
jobs:
    check-code-style:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - uses: actions/checkout@v2
            - uses: psf/black@stable
